name: Build cybr
on:
  workflow_dispatch:
    inputs:
      force_fail:
        description: "Force fail API"
        required: false
        default: "No"
        type: choice
        options: ["No", "Yes"]
jobs:
  build-os:
    runs-on: ubuntu-latest
    outputs:
      build_success: ${{ steps.set-status.outputs.success }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make syslinux syslinux-utils isolinux genisoimage squashfs-tools mtools sshpass wget xz-utils
      - name: Setup minimal ISO structure
        run: |
          mkdir -p iso/isolinux
          mkdir -p iso/boot
          mkdir -p iso/arch/boot/x86_64
          mkdir iso/arch/x86_64
          # Use smallest possible kernel
          wget -O iso/boot/vmlinuz https://raw.githubusercontent.com/WolfTech-Innovations/WLFBUILD-RESOURCE/main/vmlinuz
          
          # Create an extremely minimal initramfs with maximum compression
          wget -O iso/arch/boot/x86_64/initramfs.img https://sourceforge.net/projects/wolfos/files/initramfs-compressed-source/initramfs.img/download
          wget -O iso/arch/boot/x86_64/vmlinuz https://sourceforge.net/projects/wolfos/files/initramfs-compressed-source/vmlinuz/download
          wget -O iso/arch/x86_64/airoot.sfs https://sourceforge.net/projects/wolfos/files/initramfs-compressed-source/airoot.sfs/download
          # Download isolinux config as in original script
          wget -O iso/isolinux/isolinux.cfg https://raw.githubusercontent.com/WolfTech-Innovations/WLFBUILD-RESOURCE/main/isolinux.cfg
          
          # Copy the essential ISOLINUX files
          sudo cp /usr/lib/ISOLINUX/isolinux.bin iso/isolinux/
          sudo cp /usr/lib/syslinux/modules/bios/ldlinux.c32 iso/isolinux/
          
      - name: Create minimal ISO
        run: |
          xorriso -as mkisofs   -iso-level 3  -volid "cybr"   -output ./cybr.iso   -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin   -b boot/isolinux/isolinux.bin   -c boot.catalog   -no-emul-boot -boot-load-size 4 -boot-info-table   ./iso
          sudo chmod 777 cybr.iso
          isohybrid cybr.iso

          # Display final ISO size
          ls -lh cybr.iso
          du -h cybr.iso
      - name: Upload to SourceForge
        env:
          SF_USER: ${{ secrets.SF_USER }}
          SF_PASS: ${{ secrets.SF_PASS }}
          OSVER: 1
        run: |
          sshpass -p "$SF_PASS" scp -o StrictHostKeyChecking=no ./cybr.iso "$SF_USER@frs.sourceforge.net:/home/frs/project/wolfos/KordOS-v${OSVER}.iso"
      - uses: actions/upload-artifact@v4
        with:
          name: cybr-iso
          path: cybr.iso
      - name: Set build status
        id: set-status
        run: |
          if [[ "${{ github.event.inputs.force_fail }}" == "Yes" ]]; then
            echo "success=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "success=true" >> $GITHUB_OUTPUT
  notify-api:
    needs: build-os
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: curl --max-time 30 "${{ secrets.API_URL }}"
