name: Build WolfOS

on:
  workflow_dispatch:

jobs:
  build-wolfos:
    name: Build WolfOS (amd64)
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Restore Cache (Incremental Builds)
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            .repo
            out/
            ccache/
          key: build-amd64
          restore-keys: |
            build-amd64-

      - name: Sync Source Code
        run: |
          mkdir -p wolfos
          cd wolfos
          repo init -u https://github.com/openFyde/manifest.git -b release-R114-15437.B
          repo sync -c -j$(nproc) --force-sync --prune --no-tags --no-clone-bundle

      - name: Rebrand ChromeOS to WolfOS
        run: |
          cd wolfos
          find . -type f -name "*.xml" -exec sed -i 's/ChromeOS/WolfOS/g' {} +

      - name: Remove Boot Logo (if exists)
        run: |
          cd wolfos
          BOOTLOGO="firmware/bootlogo.bmp"
          if [ -f "$BOOTLOGO" ]; then
            echo "Removing boot logo..."
            rm -f "$BOOTLOGO"
          else
            echo "Boot logo not found, skipping."
          fi

      - name: Remove Telemetry
        run: |
          cd wolfos
          echo "Stripping telemetry..."
          grep -rlE 'metrics|telemetry|uma' . | xargs --no-run-if-empty sed -i '/metrics\|telemetry\|uma/d'

      - name: Set Up Build Environment
        run: |
          cd wolfos
          ./chromite/bin/cros_sdk -- ./setup_board --board=amd64-openfyde

      - name: Build Packages
        run: |
          cd wolfos
          ./chromite/bin/cros_sdk -- ./build_packages --board=amd64-openfyde

      - name: Build Image
        run: |
          cd wolfos
          ./chromite/bin/cros_sdk -- ./build_image --board=amd64-openfyde base

      - name: Save Cache (Incremental Builds)
        uses: actions/cache@v3
        with:
          path: |
            .repo
            out/
            ccache/
          key: build-amd64

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfOS-amd64
          path: wolfos/src/build/images/amd64-openfyde/latest/*.bin
