name: Build WolfOS

on:
  workflow_dispatch:


jobs:
  build-os:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            make \
            genisoimage \
            squashfs-tools \
            grub-pc-bin \
            xorriso \
            mtools

      # Step 3: Download the Linux Kernel
      - name: Download Linux Kernel
        run: |
          wget https://github.com/WolfTech-Innovations/WLFBUILD-RESOURCE/blob/main/vmlinuz -O vmlinuz
          mkdir iso 
          mkdir iso/boot
          mkdir iso/boot/grub
          cp ./vmlinuz iso/boot/
          wget https://github.com/WolfTech-Innovations/WLFBUILD-RESOURCE/blob/main/grub.cfg
          cp ./grub.cfg iso/boot/grub/
          wget https://github.com/WolfTech-Innovations/WLFBUILD-RESOURCE/blob/main/splash.png
          cp ./splash.png iso/boot/grub/
      # Step 6: Create bootable ISO
      - name: Create bootable ISO
        run: |
          wget https://sourceforge.net/projects/wolfos/files/initramfs-compressed-source/initramfs.cpio.gz/download -o init.cpio.gz
          mv init.cpio.gz iso/boot/
          grub-mkrescue -o wolfos.iso iso
