name: Build WolfOS

on:
  workflow_dispatch:

jobs:
  build-matrix:
    name: Build WolfOS (Matrix)
    runs-on: self-hosted
    strategy:
      matrix:
        architecture: [x86_64, arm64]
        variant: [user, userdebug, eng]
        include:
          - architecture: x86_64
            variant: userdebug
          - architecture: arm64
            variant: eng
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Required Tools and Dependencies
        run: |
          sudo apt update
          sudo apt install -y git bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev libc6-dev-i386 libgl1-mesa-dev

      - name: Install Repo Tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo -o repo
          chmod +x repo
          sudo mv repo /usr/local/bin/repo

      - name: Restore Cache (Incremental Builds)
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            .repo
            out/
            ccache/
          key: build-${{ matrix.architecture }}-${{ matrix.variant }}
          restore-keys: |
            build-${{ matrix.architecture }}-

      - name: Sync Source Code
        run: |
          mkdir -p wolfos
          cd wolfos
          repo init -u git://git.osdn.net/gitroot/android-x86/manifest -b r-x86
          repo sync -j$(nproc) --force-sync --prune --no-tags --no-clone-bundle

      - name: Integrate Lawnchair Launcher
        run: |
          cd wolfos
          mkdir -p packages/apps/Lawnchair
          cd packages/apps/Lawnchair
          wget -O Lawnchair.apk https://github.com/LawnchairLauncher/lawnchair/releases/latest/download/Lawnchair.apk
          cat <<EOF > Android.mk
          LOCAL_PATH := \$(call my-dir)

          include \$(CLEAR_VARS)
          LOCAL_MODULE := Lawnchair
          LOCAL_SRC_FILES := Lawnchair.apk
          LOCAL_MODULE_CLASS := APPS
          LOCAL_MODULE_PATH := \$(TARGET_OUT)/app
          LOCAL_MODULE_TAGS := optional
          LOCAL_CERTIFICATE := PRESIGNED
          include \$(BUILD_PREBUILT)
          EOF

      - name: Configure Features
        run: |
          cd wolfos
          echo "persist.sys.debug.multi_window=true" >> device/generic/common/build.prop
          echo "persist.sys.freeform_window_state=true" >> device/generic/common/build.prop
          echo "persist.sys.enable_freeform_support=true" >> device/generic/common/build.prop
          # Additional configurations can be added here

      - name: Lunch Configuration
        run: |
          cd wolfos
          source build/envsetup.sh
          lunch android_x86_${{ matrix.variant }}

      - name: Build Targets
        run: |
          cd wolfos
          make -j$(nproc) iso_img otapackage

      - name: Save Cache (Incremental Builds)
        uses: actions/cache@v3
        with:
          path: |
            .repo
            out/
            ccache/
          key: build-${{ matrix.architecture }}-${{ matrix.variant }}

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfOS-${{ matrix.architecture }}-${{ matrix.variant }}
          path: wolfos/out/target/product/*/*.iso

      - name: Upload OTA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfOS-OTA-${{ matrix.architecture }}-${{ matrix.variant }}
          path: wolfos/out/target/product/*/WolfOS-OTA-*.zip
