name: Build WolfOS

on:
  workflow_dispatch:

jobs:
  build-os:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            make \
            genisoimage \
            squashfs-tools \
            grub-pc-bin \
            xorriso \
            mtools

      # Step 3: Download Linux Kernel and resources
      - name: Download Linux Kernel and resources
        run: |
          mkdir iso 
          mkdir iso/boot
          mkdir iso/boot/grub

          # Download Linux kernel
          wget https://raw.githubusercontent.com/WolfTech-Innovations/WLFBUILD-RESOURCE/main/vmlinuz -O iso/boot/vmlinuz

          # Download GRUB configuration
          wget https://raw.githubusercontent.com/WolfTech-Innovations/WLFBUILD-RESOURCE/main/grub.cfg -O iso/boot/grub/grub.cfg

          # Download splash image
          wget https://raw.githubusercontent.com/WolfTech-Innovations/WLFBUILD-RESOURCE/main/splash.png -O iso/boot/grub/splash.png

          # Download initramfs from SourceForge
          wget https://sourceforge.net/projects/wolfos/files/initramfs-compressed-source/init.cpio.gz/download -O iso/boot/init.cpio.gz

      # Step 4: Create bootable ISO
      - name: Create bootable ISO
        run: |
          grub-mkrescue -o wolfos.iso iso

      # Step 5: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wolfos-iso
          path: wolfos.iso
