name: Build WolfOS

on:
  workflow_dispatch:
    inputs:
      force_fail:
        description: "Force fail API (Now used for FAILAPI.YAML)"
        required: false
        default: "No"
        type: choice
        options:
          - "No"
          - "Yes"

jobs:
  build-os:
    runs-on: ubuntu-latest
    outputs:
      build_success: ${{ steps.set-status.outputs.success }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        id: install-deps
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            make \
            genisoimage \
            squashfs-tools \
            syslinux \
            syslinux-common \
            mtools \
            xorriso \
            wget

      - name: Download Kernel & Resources
        id: download
        run: |
          set -e
          mkdir -p iso/isolinux
          wget -O iso/isolinux/vmlinuz https://raw.githubusercontent.com/WolfTech-Innovations/WLFBUILD-RESOURCE/main/vmlinuz
          wget -O iso/isolinux/initrd.img.xz https://sourceforge.net/projects/wolfos/files/initramfs-compressed-source/initrd.img.xz/download
          wget -O iso/isolinux/splash.png https://raw.githubusercontent.com/WolfTech-Innovations/WLFBUILD-RESOURCE/main/splash.png

          # Syslinux bootloader files
          cp /usr/lib/ISOLINUX/isolinux.bin iso/isolinux/
          cp /usr/lib/syslinux/modules/bios/ldlinux.c32 iso/isolinux/

          cat > iso/isolinux/syslinux.cfg <<EOF
UI menu.c32
PROMPT 0
TIMEOUT 30
DEFAULT wolfos

LABEL wolfos
  MENU LABEL Run WolfOS
  KERNEL /isolinux/vmlinuz
  APPEND initrd=/isolinux/initrd.img.xz root=/dev/ram0 rw console=tty0 rootfstype=ramfs init=/init splash
EOF

      - name: Create ISO
        id: iso
        run: |
          set -e
          genisoimage -o wolfos.iso \
            -b isolinux/isolinux.bin \
            -c isolinux/boot.cat \
            -no-emul-boot \
            -boot-load-size 4 \
            -boot-info-table \
            -J -R -V "WOLFOS" \
            iso

      - name: Install sshpass
        id: sshpass
        run: |
          set -e
          sudo apt-get install -y sshpass

      - name: Upload to SourceForge
        id: upload
        env:
          SF_USER: ${{ secrets.SF_USER }}
          SF_PASS: ${{ secrets.SF_PASS }}
          OSVER: 1
        run: |
          set -e
          sshpass -p "$SF_PASS" scp -o StrictHostKeyChecking=no ./wolfos.iso \
            "$SF_USER@frs.sourceforge.net:/home/frs/project/wolfos/WolfOS-v${OSVER}.iso"

      - name: Upload Artifacts
        id: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wolfos-iso
          path: wolfos.iso

      - name: Set build status
        id: set-status
        run: |
          if [[ "${{ github.event.inputs.force_fail }}" == "Yes" ]]; then
            echo "Forced failure."
            echo "success=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ "${{ steps.install-deps.outcome }}" == "failure" || \
                "${{ steps.download.outcome }}" == "failure" || \
                "${{ steps.iso.outcome }}" == "failure" || \
                "${{ steps.sshpass.outcome }}" == "failure" || \
                "${{ steps.upload.outcome }}" == "failure" || \
                "${{ steps.artifacts.outcome }}" == "failure" ]]; then
            echo "Detected failure in steps."
            echo "success=false" >> $GITHUB_OUTPUT
          else
            echo "All steps succeeded."
            echo "success=true" >> $GITHUB_OUTPUT
          fi

  notify-api:
    needs: build-os
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify API
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
            curl "$API_URL" set timeout=30
