name: Build WolfOS

on:
  workflow_dispatch:

jobs:
  build-matrix:
    name: Build WolfOS (Matrix)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, arm64]
        variant: [user, userdebug, eng]
        include:
          - architecture: x86_64
            variant: userdebug
          - architecture: arm64
            variant: eng
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Required Tools and Dependencies
        run: |
          sudo apt update
          sudo apt install -y git bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev libc6-dev-i386 libgl1-mesa-dev

      - name: Install Repo Tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo -o repo
          chmod +x repo
          sudo mv repo /usr/local/bin/repo

      - name: Restore Cache (Incremental Builds)
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            .repo
            out/
            ccache/
          key: build-${{ matrix.architecture }}-${{ matrix.variant }}
          restore-keys: |
            build-${{ matrix.architecture }}-

      - name: Sync Source Code
        run: |
          repo init -u git://gitscm.sf.net/gitroot/android-x86/manifest -b pie-x86
          repo sync -j$(nproc) --force-sync --prune --no-tags --no-clone-bundle

      - name: Apply Performance Tweaks
        run: |
          echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf
          echo 'vm.vfs_cache_pressure=50' | sudo tee -a /etc/sysctl.conf
          echo 'kernel.sched_migration_cost_ns=5000000' | sudo tee -a /etc/sysctl.conf

      - name: Lunch Configuration
        run: |
          source build/envsetup.sh
          lunch cm_${{ matrix.architecture }}-${{ matrix.variant }}

      - name: Build Targets
        run: |
          make -j$(nproc) iso_img otapackage

      - name: Save Cache (Incremental Builds)
        uses: actions/cache@v3
        with:
          path: |
            .repo
            out/
            ccache/
          key: build-${{ matrix.architecture }}-${{ matrix.variant }}

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfOS-${{ matrix.architecture }}-${{ matrix.variant }}
          path: out/target/product/*/*.iso

      - name: Upload OTA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfOS-OTA-${{ matrix.architecture }}-${{ matrix.variant }}
          path: out/target/product/*/WolfOS-OTA-*.zip
