name: Build WolfOS

on:
  workflow_dispatch:

jobs:
  build-matrix:
    name: Build WolfOS (Matrix)
    runs-on: self-hosted
    strategy:
      matrix:
        architecture: [x86_64, arm64]
        variant: [user, userdebug, eng]
        include:
          - architecture: x86_64
            variant: userdebug
          - architecture: arm64
            variant: eng
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Required Tools and Dependencies
        run: |
          sudo apt update
          packages=(
            git bc bison build-essential curl flex g++-multilib gcc-multilib
            gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev
            lib32z1-dev libc6-dev-i386 libgl1-mesa-dev
          )

          for pkg in "${packages[@]}"; do
            if dpkg -l | grep -q "$pkg"; then
              echo "$pkg is already installed, skipping."
            else
              echo "Installing $pkg..."
              sudo apt install -y $pkg
            fi
          done

      - name: Install Repo Tool
        run: |
          if ! command -v repo &> /dev/null; then
            curl https://storage.googleapis.com/git-repo-downloads/repo -o repo
            chmod +x repo
            sudo mv repo /usr/local/bin/repo
          else
            echo "Repo tool is already installed, skipping."
          fi

      - name: Restore Cache (Incremental Builds)
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            .repo
            out/
            ccache/
          key: build-${{ matrix.architecture }}-${{ matrix.variant }}
          restore-keys: |
            build-${{ matrix.architecture }}-

      - name: Sync Source Code
        run: |
          mkdir -p wolfos
          cd wolfos
          repo init -u https://chromium.googlesource.com/chromiumos/manifest -b release-R114-15437.B
          repo sync -j$(nproc) --force-sync --prune --no-tags --no-clone-bundle

      - name: Configure Features
        run: |
          cd wolfos
          echo "persist.sys.debug.multi_window=true" >> device/generic/common/build.prop
          echo "persist.sys.freeform_window_state=true" >> device/generic/common/build.prop
          echo "persist.sys.enable_freeform_support=true" >> device/generic/common/build.prop
          echo "chrome.browser.history.enabled=false" >> device/generic/common/build.prop
          echo "persist.chrome.homepage=alphasearch.pages.dev" >> device/generic/common/build.prop
          echo "persist.chrome.enable_touchscreen=true" >> device/generic/common/build.prop

      - name: Set Up Wallpaper Download
        run: |
          cd wolfos
          wget -O /home/chronos/user/Downloads/wolfos_wallpaper.jpg https://avatars.githubusercontent.com/u/147162816?v=4
          # Make sure wallpaper sets on login
          mkdir -p /etc/xdg/autostart
          cat <<EOF > /etc/xdg/autostart/set-wallpaper.desktop
          [Desktop Entry]
          Type=Application
          Exec=sh -c "gsettings set org.gnome.desktop.background picture-uri file:///home/chronos/user/Downloads/wolfos_wallpaper.jpg"
          Name=Set WolfOS Wallpaper
          Comment=Automatically set WolfOS wallpaper on startup
          EOF

      - name: Lunch Configuration
        run: |
          cd wolfos
          source build/envsetup.sh
          lunch chromiumos_${{ matrix.variant }}

      - name: Build Targets
        run: |
          cd wolfos
          make -j$(nproc) iso_img otapackage

      - name: Save Cache (Incremental Builds)
        uses: actions/cache@v3
        with:
          path: |
            .repo
            out/
            ccache/
          key: build-${{ matrix.architecture }}-${{ matrix.variant }}

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfOS-${{ matrix.architecture }}-${{ matrix.variant }}
          path: wolfos/out/target/product/*/*.iso

      - name: Upload OTA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfOS-OTA-${{ matrix.architecture }}-${{ matrix.variant }}
          path: wolfos/out/target/product/*/WolfOS-OTA-*.zip
