name: Send response to API

on:
  workflow_dispatch:
    inputs:
      force_fail:
        description: "Force fail"
        required: false
        default: "No"
        type: choice
        options:
          - "No"
          - "Yes"

jobs:
  build-os:
    runs-on: ubuntu-latest
    outputs:
      build_success: ${{ steps.set-status.outputs.success }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        id: install-deps
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            make \
            genisoimage \
            squashfs-tools \
            grub-pc-bin \
            xorriso \
            mtools
          
      - name: Set build status
        id: set-status
        run: |
          if [[ "${{ github.event.inputs.force_fail }}" == "Yes" ]]; then
            echo "Forced failure."
            echo "success=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ "${{ steps.install-deps.outcome }}" == "failure" || \
            echo "Detected failure in steps."
            echo "success=false" >> $GITHUB_OUTPUT
          else
            echo "All steps succeeded."
            echo "success=true" >> $GITHUB_OUTPUT
          fi

  notify-api:
    needs: build-os
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify API
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
            curl "$API_URL/fail"
