name: Send response to API

on:
  workflow_dispatch:
    inputs:
      force_fail:
        description: "Force fail"
        required: false
        default: "No"
        type: choice
        options:
          - "No"
          - "Yes"

jobs:
  notify-api:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify API
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
            curl "$API_URL/fail"
