name: Send failure response to API

on:
  workflow_dispatch:
    inputs:
      force_fail:
        description: "Force fail"
        required: true
        default: "Yes"
        type: choice
        options:
          - "-"
          - "Yes"

jobs:
  notify-api:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify API
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
            curl "$API_URL/fail"
